CLIENT_ID = ''
CLIENT_SECRET = ''
REDIRECT_URI = ''
SCOPE = (
'user-read-playback-state '
'user-modify-playback-state '
'user-read-currently-playing '
'playlist-read-private '
'playlist-read-collaborative '
'playlist-modify-public '
'playlist-modify-private '
'user-library-read '
'user-library-modify '
'app-remote-control '
'streaming'
)
